api = "0.11"

[buildpack]
id = "io.build.github.buildio.buildpack-apt"
version = "0.0.20"
name = "apt Packages Buildpack"
homepage = "https://github.com/buildio/buildpack-apt"
description = "Installs apt packages for further builds and runtime"
keywords = ["apt", "packages", "ubuntu"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "*"

[[targets]]
os = "linux"
